---
title: "IUPUI Causal Team"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

We are a team working under <a href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=1948322&HistoricalAwards=false">NSF Award Number 1948322: "Capturing Dynamism in Causal Relationships: A New Paradigm for Relationship Extraction from Text"</a>. The principal investigator is Dr. Sunandan Chakraborty, a data science professor at Indiana University-Purdue University of Indianapolis (IUPUI). Our team consists of both graduate and undergraduate research assistants in the school of informatics at IUPUI.

Our work involves data science, natural language processing, and deep learning. We are investigating and developing  methods for mining relationships expressed in text using deep neural networks. Particularly, our current research aims not only identify causal relationships in text, but also assess their strength in an unsupervised manner. 